services:
  - type: web
    name: base-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
